/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author PC
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        
        
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),40,40));
    }
    
    
    
    
    
    //method to insert value in users table
    public void insertSignupDetails(){
        String name = txtusername.getText();
        String pw = txtpassword.getText();
        String email = txtEmail.getText();
        String contact = txtConatct.getText();
        
        try{
            
            Connection con = DBConnection.getConnection();
            
            String sql = "insert into users(name,password,email,contact)values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1,name);
            pst.setString(2,pw);
            pst.setString(3,email);
            pst.setString(4,contact);
            
            int updatedRowCount = pst.executeUpdate();
            
            if(updatedRowCount >0){
                JOptionPane.showMessageDialog(this,"Record inserted succesfully");
            }
            else{
                JOptionPane.showMessageDialog(this,"Record inserte fails");
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
               
    }
    
    
    //check for duplicate users
      public boolean checkDuplicateUser(){
        String name =  txtusername.getText();
        boolean isExist = false;
        
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/car_rental_ms","root","");
            // con = DBconnection.getConnection();
            
            PreparedStatement pst = con.prepareStatement("Select * from users where name =?");
            pst.setString(1, name);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                isExist = true;
            }
            else{
                isExist=false;
            }
            
        }
        catch(Exception ex){
            ex.getStackTrace();
        }
       return isExist;
    }   
    
      
      //validation //validation
    
    public boolean validateSignUp(){
        
        String name = txtusername.getText();
        String pw = txtpassword.getText();
        String email = txtEmail.getText();
        String contact = txtConatct.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter name");
            return false;
        }
        
         if(email.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter email");
            return false;
        }
         
          if(pw.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter password");
            return false;
        }
          
           if(contact.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter contact");
            return false;
        }
        
        return true;
    }
      
      
      
      
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtConatct = new rojerusan.RSMetroTextPlaceHolder();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtusername = new rojerusan.RSMetroTextPlaceHolder();
        txtpassword = new rojerusan.RSMetroTextPlaceHolder();
        txtEmail = new rojerusan.RSMetroTextPlaceHolder();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(958, 543));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,190));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jLabel3.setText(" UserName  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, 29));

        txtConatct.setForeground(new java.awt.Color(153, 0, 153));
        txtConatct.setBorderColor(new java.awt.Color(153, 0, 153));
        txtConatct.setCaretColor(new java.awt.Color(255, 255, 255));
        txtConatct.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtConatct.setPhColor(new java.awt.Color(204, 0, 204));
        txtConatct.setPlaceholder("Enter Contact No...");
        jPanel1.add(txtConatct, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 250, -1));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(51, 0, 51));
        rSMaterialButtonRectangle2.setText("SIGNUP");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 181, 45));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.png"))); // NOI18N
        jLabel6.setText(" Password  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, 29));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        jLabel7.setText(" Email          :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 120, 29));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receiver.png"))); // NOI18N
        jLabel8.setText(" Contact No:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, 29));

        txtusername.setForeground(new java.awt.Color(153, 0, 153));
        txtusername.setBorderColor(new java.awt.Color(153, 0, 153));
        txtusername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusername.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtusername.setPhColor(new java.awt.Color(204, 0, 204));
        txtusername.setPlaceholder("Enter UserName...");
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 250, -1));

        txtpassword.setForeground(new java.awt.Color(153, 0, 153));
        txtpassword.setBorderColor(new java.awt.Color(153, 0, 153));
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtpassword.setPhColor(new java.awt.Color(204, 0, 204));
        txtpassword.setPlaceholder("Enter Password...");
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 250, -1));

        txtEmail.setForeground(new java.awt.Color(153, 0, 153));
        txtEmail.setBorderColor(new java.awt.Color(153, 0, 153));
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtEmail.setPhColor(new java.awt.Color(204, 0, 204));
        txtEmail.setPlaceholder("Enter Email...");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 250, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sport-car.png"))); // NOI18N
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(60, 110, 120, 90);

        jLabel10.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("WELLCOME BACK !");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(60, 70, 180, 22);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("If you have an Account");
        kGradientPanel1.add(jLabel12);
        jLabel12.setBounds(60, 230, 144, 18);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Please Login here.");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(70, 250, 117, 18);

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 0, 153));
        rSMaterialButtonRectangle1.setText("LOGIN");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSMaterialButtonRectangle1);
        rSMaterialButtonRectangle1.setBounds(30, 280, 181, 45);

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 410));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGNUP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 150, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 70, 660, 410);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(930, 10, 20, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaperflare.com_wallpaper (4).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 980, 580);

        setSize(new java.awt.Dimension(958, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        if(validateSignUp()==true){
        insertSignupDetails();    
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        if(checkDuplicateUser()== true){
            JOptionPane.showInternalMessageDialog(this,"username already exist");
        }
    }//GEN-LAST:event_txtusernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMetroTextPlaceHolder txtConatct;
    private rojerusan.RSMetroTextPlaceHolder txtEmail;
    private rojerusan.RSMetroTextPlaceHolder txtpassword;
    private rojerusan.RSMetroTextPlaceHolder txtusername;
    // End of variables declaration//GEN-END:variables
}
