/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import carrentalmanagementsystem.*;
import java.awt.geom.RoundRectangle2D;


/**
 *
 * @author PC
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        //roundForm
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),40,40));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        lblLoadingvalue = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(665, 390));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallpaperflare.com_wallpaper (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 380);

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 204));
        jLabel3.setText("THISARA'S ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 70, 240, 90);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 204));
        jLabel4.setText("CAR RENTAL SERVICE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 110, 450, 90);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sport-car.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 170, 128, 128);

        ProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ProgressBar);
        ProgressBar.setBounds(-2, 380, 670, 20);

        lblLoadingvalue.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblLoadingvalue.setForeground(new java.awt.Color(204, 0, 0));
        lblLoadingvalue.setText("0%");
        jPanel1.add(lblLoadingvalue);
        lblLoadingvalue.setBounds(630, 360, 30, 20);

        lblLoading.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(204, 0, 0));
        lblLoading.setText("Loading....");
        jPanel1.add(lblLoading);
        lblLoading.setBounds(430, 360, 190, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(665, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
          
       Splash sp = new Splash();
       sp.setVisible(true);
       Login l = new  Login();
                   
       
       try{
           
           for(int i = 0; i<=100;i++){
               Thread.sleep(100);
               sp.lblLoadingvalue.setText(i+"%");
               
               if(i==10){
                   sp.lblLoading.setText("Turning on Modules...");
                   
               }
               if(i==20){
                   sp.lblLoading.setText("Loading on Modules...");
                   
               }
               if(i==50){
                   sp.lblLoading.setText("Connecting to Database...");
                   
               }
               if(i==70){
                   sp.lblLoading.setText("Connection Successful !");
                   
               }
               if(i==80){
                   sp.lblLoading.setText("Launching Application...");
                   
               }
             
               sp.ProgressBar.setValue(i);
               
           }
           
       }
       catch(Exception ex){
           ex.printStackTrace();
       }
       
       sp.setVisible(false);
       l.setVisible(true);
       
       sp.dispose();
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoadingvalue;
    // End of variables declaration//GEN-END:variables
}
